version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:1.7
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
      - 8443:443
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      DB_PREFIX: _ps
    volumes:
      - ./html:/var/www/html
      - ./html/cert.crt:/etc/ssl/cert.crt
      - ./html/key.key:/etc/ssl/private/key.key
      - ./html/000-default.conf:/etc/apache2/sites-available/000-default.conf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8081:80