version: '3'
services:
  prestashop:
    image: kasiastachu/biznes_elektroniczny:1.6
    restart: unless-stopped
    ports:
      - 18875:443
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      DB_SERVER: db
      DB_NAME: BE_188756
      DB_USER: root
      DB_PASSWD: student
      DB_PREFIX: _ps
      ADMIN_FOLDER: ${ADMIN_FOLDER:-admin-dev}
      ADMIN_MAIL: ${ADMIN_MAIL:-demo@prestashop.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-prestashop_demo}
    networks:
      - admin-mysql_default
  memcached:
    image: memcached
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - admin-mysql_default
networks:
  admin-mysql_default:
    external: true